"""add_tickets_table

Revision ID: 20a07245ffe9
Revises: a474c8c94c46
Create Date: 2026-02-22 20:20:33.356428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a07245ffe9'
down_revision: Union[str, None] = 'a474c8c94c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticketTitle', sa.String(length=255), nullable=False),
    sa.Column('ticketDescription', sa.Text(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Label', sa.String(length=50), nullable=False),
    sa.Column('thumb', sa.String(length=500), nullable=True),
    sa.Column('AgentName', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['super_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
