"""Add profile fields to SuperAdmin

Revision ID: 9400fce0d339
Revises: 9c1c94b82a58
Create Date: 2026-02-22 13:25:19.820899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9400fce0d339'
down_revision: Union[str, None] = '9c1c94b82a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'primary_branch_id',
               existing_type=mysql.INTEGER(),
               comment='Primary branch for branch-level roles (BRANCH_ADMIN, BRANCH_PRINCIPAL)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'primary_branch_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Primary branch for branch-level roles (BRANCH_ADMIN, BRANCH_PRINCIPAL)',
               existing_nullable=True)
    # ### end Alembic commands ###
