"""sync_master_models

Revision ID: 62f978228f28
Revises: 2bd687eff861
Create Date: 2026-02-23 14:08:00.103492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f978228f28'
down_revision: Union[str, None] = '2bd687eff861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('yearly_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_plan_name'), 'subscription_plans', ['plan_name'], unique=True)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('datef', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['super_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticketTitle', sa.String(length=255), nullable=False),
    sa.Column('ticketDescription', sa.Text(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Label', sa.String(length=50), nullable=False),
    sa.Column('thumb', sa.String(length=500), nullable=True),
    sa.Column('AgentName', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['super_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.add_column('super_admins', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('super_admins', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('super_admins', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('super_admins', sa.Column('state', sa.String(length=200), nullable=True))
    op.add_column('super_admins', sa.Column('pin', sa.String(length=20), nullable=True))
    op.add_column('super_admins', sa.Column('zip', sa.String(length=20), nullable=True))
    op.add_column('super_admins', sa.Column('tax_no', sa.String(length=50), nullable=True))
    op.add_column('super_admins', sa.Column('facebook_url', sa.String(length=255), nullable=True))
    op.add_column('super_admins', sa.Column('twitter_url', sa.String(length=255), nullable=True))
    op.add_column('super_admins', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('super_admins', sa.Column('dribbble_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admins', 'dribbble_url')
    op.drop_column('super_admins', 'github_url')
    op.drop_column('super_admins', 'twitter_url')
    op.drop_column('super_admins', 'facebook_url')
    op.drop_column('super_admins', 'tax_no')
    op.drop_column('super_admins', 'zip')
    op.drop_column('super_admins', 'pin')
    op.drop_column('super_admins', 'state')
    op.drop_column('super_admins', 'location')
    op.drop_column('super_admins', 'position')
    op.drop_column('super_admins', 'phone')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_subscription_plans_plan_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
